artifact_uri: file:///Users/michaelnatterer/telco-churn-deployment/monitoring/mlflow_runs/794669761400459628/3afdabc3629e4cb89fcb82bc4311ca5f/artifacts
end_time: 1761741271435
entry_point_name: ''
experiment_id: '794669761400459628'
lifecycle_stage: active
run_id: 3afdabc3629e4cb89fcb82bc4311ca5f
run_name: Model Evaluation (JSON)
run_uuid: 3afdabc3629e4cb89fcb82bc4311ca5f
source_name: ''
source_type: 4
source_version: ''
start_time: 1761741271429
status: 3
tags: []
user_id: michaelnatterer
