artifact_location: file:///Users/michaelnatterer/telco-churn-deployment/monitoring/mlflow_runs/794669761400459628
creation_time: 1761741271113
experiment_id: '794669761400459628'
last_update_time: 1761741271113
lifecycle_stage: active
name: Telco Churn Monitoring
