artifact_uri: file:///Users/michaelnatterer/telco-churn-deployment/monitoring/mlflow_runs/794669761400459628/1ec5c8da04b64cb885a84c2b7ade1f3e/artifacts
end_time: 1761741903834
entry_point_name: ''
experiment_id: '794669761400459628'
lifecycle_stage: active
run_id: 1ec5c8da04b64cb885a84c2b7ade1f3e
run_name: Model Evaluation (JSON + Threshold)
run_uuid: 1ec5c8da04b64cb885a84c2b7ade1f3e
source_name: ''
source_type: 4
source_version: ''
start_time: 1761741903826
status: 3
tags: []
user_id: michaelnatterer
