name: Evidently Drift Report

on:
  schedule:
    - cron: "0 0 1 * *"   # Läuft am 1. jeden Monats um 00:00 UTC
  workflow_dispatch:       # Manuell auslösbar im GitHub-UI

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install evidently==0.3.2 pandas

      - name: Generate Evidently Drift Report
        run: python monitoring/evidently_drift.py

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: evidently-drift-report
          path: monitoring/evidently_reports/